name: Retrieve Gemfiles

on:
  workflow_call:

jobs:
  fetch:
    name: Retrieve Gemfiles
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Remove existing Gemfile and Gemfile.lock
      run: |
        rm -rf Gemfile Gemfile.lock
        mkdir ./gemfiles
    - name: Download Gemfile and Gemfile.lock
      run: |
        curl https://github.com/ietf-ribose/bibxml-service/raw/gemfilelock/Gemfile -o gemfiles/Gemfile
        curl https://github.com/ietf-ribose/bibxml-service/raw/gemfilelock/Gemfile.lock -o gemfiles/Gemfile.lock
    - name: less Gemfile
      run: |
        less gemfiles/Gemfile
        less gemfiles/Gemfile.lock
    - name: ls
      run: ls gemfiles
    - name: mv Gemfile and Gemfile.lock
      run: mv -t . gemfiles/Gemfile gemfiles/Gemfile.lock
    - name: Push data
      run: |
        git config user.name ietf-bib-bot
        git config user.email gh-bib-bot@llc.ietf.org
        git add Gemfile Gemfile.lock
        git diff --quiet && git diff --staged --quiet || (git commit -m 'update Gemfile and Gemfile.lock' && git push)

