name: Retrieve Gemfiles

on:
  workflow_call:

jobs:
  fetch:
    name: Retrieve Gemfiles
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Remove existing Gemfile and Gemfile.lock
      run: rm -rf Gemfile Gemfile.lock
    - name: Download Gemfile and Gemfile.lock
      run: curl --remote-name-all https://github.com/ietf-ribose/bibxml-service/raw/gemfilelock/{Gemfile,Gemfile.lock}
    - name: less Gemfile
      run: |
        less Gemfile
        less Gemfile.lock
        ls
    - name: Push data
      run: |
        git config user.name ietf-bib-bot
        git config user.email gh-bib-bot@llc.ietf.org
        git add Gemfile Gemfile.lock
        git diff --quiet && git diff --staged --quiet || (git commit -m 'update Gemfile and Gemfile.lock' && git push)

